name: build react app

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.2.0
        
      - name: install node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 14
          
      - name: cache node moudules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node_cache_${{ hashFiles('**/package-lock.json') }}
          
      - name: download dependencies
        run: npm ci
        
      - name: build app
        run: npm run build
      
      - name: upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: app
          path: ./build/
        
      
